### PR TITLE
Fix metadata and add outputs section

### PR DESCRIPTION
**Pull request by toricls**
This PR fixes `Metadata` section and adds `Outputs` section to obtain the endpoint of the deployed App Runner service.

### CODE REVIEW

**Comment by rothgar** [comment]
Sorry I didn't get back to you on this yet. I tried deploying this template to the console and I still get an error. I haven't had time this week to figure out why.

image

**Comment by rothgar** [comment]
Your cloudformation file does work via cli. I'm not sure why the designer gives me this error. Would you mind updating it with a parameter for the service name and adding an example to the README for how people can use it from the cli

Something like this should be enough
```
aws cloudformation create-stack --template-body file://cf.yaml --stack-name hello-app-runner 
```

here's the modified cloudformation file I ended up with
```
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
Parameters:
  ServiceName:
    Type: String
    Default: hello-app-runner
    Description: Name for your App Runner service.
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template that deploys hello-app-runner app
Resources:
  Service:
    Metadata:
      'aws:apprunner:description': 'hello-app-runner example service'
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName:
        Ref: ServiceName
      SourceConfiguration:
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageIdentifier: public.ecr.aws/aws-containers/hello-app-runner:latest
          ImageRepositoryType: ECR_PUBLIC
          ImageConfiguration:
            Port: 8000
Outputs:
  Endpoint:
    Description: "The endpoint of the App Runner service."
    Value: !GetAtt Service.ServiceUrl
```

**Comment by toricls** [comment]
Update the template and add an example in README!
(I also changed the base branch to `main` since I accidentally rebased my branch from it... Let me know if you'd like the base branch to keep `cf-button` then I'll recreate the branch :)

**Comment by rothgar** [comment]
LGTM :+1:

**Review by rothgar — APPROVED** [review]

**Pull request merged**
